// Verbatim captured GraphQL document for UpdateFilters (reverse-engineered, do not edit).
import type { Operation } from "../core/graphql";

export const updateFilters: Operation = {
  name: "UpdateFilters",
  id: "32544b66a5cc005ae1e853bb7896aa82b2bfce865f3e69cb64486ff92475a458",
  rootField: "searchListingsByQuery",
  document:
    "query UpdateFilters($categoryId: ID, $query: String, $constraints: ListingSearchConstraints) { searchListingsByQuery(category: $categoryId, query: $query, constraints: $constraints) { selectedCategory { __typename ...categoryFields } suggestedCategories(first: 2) { __typename ...categoryFields } filters { __typename ...filterFields } listings { totalCount } searchToken } }  fragment categoryFields on Category { categoryID label parent { categoryID label } }  fragment filterDescriptionFields on ListingsFilterDescription { disabled name label }  fragment intervalTypeTextFields on ListingIntervalTypeText { minLimit maxLimit }  fragment intervalTypeSliderFields on ListingIntervalTypeSlider { sliderStart: minLimit sliderEnd: maxLimit }  fragment intervalFilterFields on ListingIntervalFilter { __typename ...filterDescriptionFields intervalType { __typename ... on ListingIntervalTypeText { __typename ...intervalTypeTextFields } ... on ListingIntervalTypeSlider { __typename ...intervalTypeSliderFields } } intervalValue: value { min max } step unit minField { placeholder } maxField { placeholder } }  fragment selectOptionFields on ListingSelectOption { __typename value label }  fragment singleSelectFilterFields on ListingSingleSelectFilter { __typename ...filterDescriptionFields placeholder inline selectedOption: value options { __typename ...selectOptionFields } }  fragment multiSelectFilterFields on ListingMultiSelectFilter { __typename ...filterDescriptionFields placeholder inline selectedOptions: values options { __typename ...selectOptionFields } }  fragment pricingFilterFields on ListingPricingFilter { __typename ...filterDescriptionFields pricingValue: value { min max freeOnly } minField { placeholder } maxField { placeholder } }  fragment localityFields on Locality { localityID name localityType }  fragment catalogLocationFilterFields on ListingLocationFilter { __typename ...filterDescriptionFields placeholder locationValue: value { selectedLocalities { __typename ...localityFields } radius } }  fragment filterFields on ListingFilter { __typename ...filterDescriptionFields ... on ListingIntervalFilter { __typename ...intervalFilterFields } ... on ListingSingleSelectFilter { __typename ...singleSelectFilterFields } ... on ListingMultiSelectFilter { __typename ...multiSelectFilterFields } ... on ListingPricingFilter { __typename ...pricingFilterFields } ... on ListingLocationFilter { __typename ...catalogLocationFilterFields } }",
};
